name: Generate Changeset

# This workflow can be triggered in two ways:
# 1. By adding the 'ready-for-changeset' label to a pull request
# 2. Manually via the GitHub Actions UI using the workflow_dispatch event
#    - Go to Actions > Generate Changeset > Run workflow
#    - Enter the PR number and click "Run workflow"

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to generate changeset for'
        required: true
        type: string

jobs:
  generate-changeset:
    if: (github.event_name == 'pull_request' && github.event.label.name == 'ready-for-changeset') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
          # Use a personal access token with repo scope for better permissions
          token: ${{ secrets.REPO_PAT }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Extract PR information
        id: pr_info
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            PR_NUMBER="${{ github.event.inputs.pr_number }}"
          else
            PR_NUMBER="${{ github.event.pull_request.number }}"
          fi
          
          PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.REPO_PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}")
          
          PR_TITLE=$(echo "$PR_DATA" | jq -r '.title')
          PR_BODY=$(echo "$PR_DATA" | jq -r '.body')
          PR_AUTHOR=$(echo "$PR_DATA" | jq -r '.user.login')
          
          echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "pr_title=${PR_TITLE}" >> $GITHUB_OUTPUT
          echo "pr_author=${PR_AUTHOR}" >> $GITHUB_OUTPUT
          echo "pr_body=${PR_BODY}" >> $GITHUB_OUTPUT
          
      - name: Generate changeset
        run: |
          npm run changeset:generate -- \
            --pr=${{ steps.pr_info.outputs.pr_number }} \
            --title="${{ steps.pr_info.outputs.pr_title }}" \
            --author="${{ steps.pr_info.outputs.pr_author }}" \
            --body="${{ steps.pr_info.outputs.pr_body }}"
          
      - name: Commit changeset
        # The GITHUB_TOKEN is automatically used by this action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: add changeset for PR #${{ steps.pr_info.outputs.pr_number }}"
          file_pattern: ".changesets/*.md"
          branch: develop
          commit_options: '--no-verify'
          push_options: '--force'
        env:
          # Set the GITHUB_TOKEN to REPO_PAT for better permissions
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
          
      - name: Remove label
        if: github.event_name == 'pull_request'
        run: |
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.REPO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/ready-for-changeset" 