name: Release Management

on:
  # Using pull_request_target instead of pull_request for security reasons:
  # - Runs in the context of the BASE repository, not the fork
  # - Has access to repository secrets
  # - Can commit changes to protected branches
  # - SECURITY NOTE: Be careful when checking out PR code with this event type
  pull_request_target:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Force a specific release type (leave empty for auto-detection)'
        required: false
        type: choice
        options:
          - auto
          - major
          - minor
          - patch
        default: 'auto'
      target_branch:
        description: 'Target branch for manual release (usually develop)'
        required: false
        default: 'develop'
  schedule:
    # Run on the 1st and 15th of each month
    - cron: '0 0 1,15 * *'

jobs:
  prepare-release:
    # Only run if:
    # 1. PR from develop to main is merged, OR
    # 2. Manually triggered, OR
    # 3. Scheduled run
    if: (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'develop') || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Set checkout ref
        id: set_ref
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            echo "ref=main" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ github.event.inputs.target_branch || 'develop' }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # For PR events, check out the main branch
          # For manual/scheduled events, check out the specified target branch or develop
          ref: ${{ steps.set_ref.outputs.ref }}
          # Use a personal access token with repo scope for better permissions
          token: ${{ secrets.REPO_PAT }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Check for changesets
        id: check_changesets
        run: |
          if [ -d ".changesets" ] && [ "$(ls -A .changesets)" ]; then
            echo "has_changesets=true" >> $GITHUB_OUTPUT
          else
            echo "has_changesets=false" >> $GITHUB_OUTPUT
            echo "No changesets found. Exiting."
            exit 1
          fi
          
      - name: Determine version bump
        id: version_bump
        run: |
          if [[ "${{ github.event.inputs.release_type }}" != "auto" && "${{ github.event.inputs.release_type }}" != "" ]]; then
            # Use the specified release type
            npm run version:bump -- --type=${{ github.event.inputs.release_type }}
          else
            # Auto-detect release type from changesets
            npm run version:bump
          fi
          
          # Get the new version after bump
          NEW_VERSION=$(grep -oP "define\('AUTOMATION_TESTS_VERSION', '\K[^']+" constants.php)
          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          
      - name: Update changelogs
        run: |
          npm run changelogs:update -- --version=${{ steps.version_bump.outputs.version }}
          
      - name: Generate release notes
        id: release_notes
        run: |
          # Generate release notes directly using our script
          npm run release:notes > release_notes.md
          
          # For debugging
          echo "Generated release notes:"
          cat release_notes.md
          
          # Set the content for GitHub Actions output
          # Properly escape the content for GitHub Actions
          RELEASE_NOTES=$(cat release_notes.md)
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
          
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      # For non-PR events (manual/scheduled), commit changes to develop
      - name: Commit changes to develop
        if: github.event_name != 'pull_request_target'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "release: prepare v${{ steps.version_bump.outputs.version }}"
          file_pattern: "*.php *.md *.txt package.json"
          # For manual/scheduled events, commit to the specified target branch or develop
          branch: ${{ github.event.inputs.target_branch || 'develop' }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
          
      # For PR events, handle all main branch operations
      - name: Commit changes to main
        if: github.event_name == 'pull_request_target'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if there are any changes to commit
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected, committing to main branch"
            git add *.php *.md *.txt package.json
            git commit -m "release: prepare v${{ steps.version_bump.outputs.version }}"
            git push origin main
          else
            echo "No changes to commit"
          fi
          
      - name: Create and push tag
        if: github.event_name == 'pull_request_target'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if tag already exists
          if git rev-parse "v${{ steps.version_bump.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ steps.version_bump.outputs.version }} already exists. Skipping tag creation."
          else
            # Create an annotated tag with the changelog as the message
            git tag -a "v${{ steps.version_bump.outputs.version }}" -m "Release v${{ steps.version_bump.outputs.version }}"
            
            # Push the tag
            git push origin "v${{ steps.version_bump.outputs.version }}"
          fi
          
      - name: Create GitHub Release
        if: github.event_name == 'pull_request_target'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        with:
          tag_name: v${{ steps.version_bump.outputs.version }}
          release_name: Release v${{ steps.version_bump.outputs.version }}
          body: ${{ steps.release_notes.outputs.content }}
          draft: false
          prerelease: false
          
      - name: Archive changesets
        if: github.event_name == 'pull_request_target'
        run: |
          # Create archive directory if it doesn't exist
          mkdir -p .changesets/archive
          
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if there are any changesets to archive
          if [ -n "$(find .changesets -maxdepth 1 -name "*.md" -type f)" ]; then
            # List all changesets before moving
            echo "Changesets to archive:"
            find .changesets -maxdepth 1 -name "*.md" -type f -exec basename {} \;
            
            # Move each changeset individually and add to Git
            for file in $(find .changesets -maxdepth 1 -name "*.md" -type f); do
              filename=$(basename "$file")
              echo "Moving $filename to archive"
              git mv "$file" ".changesets/archive/$filename"
            done
            
            # Commit the archived changesets
            git commit -m "chore: archive changesets for v${{ steps.version_bump.outputs.version }}"
            git push origin main
            
            echo "Archived changesets for v${{ steps.version_bump.outputs.version }}"
          else
            echo "No changesets found to archive"
          fi
          
      # Sync all changes back to develop after release is complete
      - name: Sync changes to develop branch
        if: github.event_name == 'pull_request_target'
        run: |
          # Configure Git if not already configured
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          echo "Syncing all changes from main to develop branch"
          
          # Fetch the latest develop branch
          git fetch origin develop
          
          # Create a temporary branch from develop
          git checkout -b temp-sync-develop origin/develop
          
          # Merge changes from main (without committing yet)
          git merge --no-commit --no-ff origin/main
          
          # Check if there are changes to commit
          if [[ -n "$(git status --porcelain)" ]]; then
            # Add all changes
            git add .
            
            # Commit the changes
            git commit -m "chore: sync changes from v${{ steps.version_bump.outputs.version }} release"
            
            # Push the changes to develop
            git push origin temp-sync-develop:develop
            
            echo "Successfully synced all changes to develop branch"
          else
            echo "No changes to sync to develop branch"
          fi
          
          # Clean up - switch back to main
          git checkout main 